# Generated by Django 3.2.4 on 2021-06-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_quantity'),
        ('orders', '0002_deliverydate'),
    ]

    operations = [
    ]
