# Generated by Django 3.2.4 on 2021-06-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taste',
            old_name='taste',
            new_name='name',
        ),
    ]
